name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: InfraWay/delete-workflow-runs@v2.1.2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 4
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: MetaCubeX/metacubexd
          fetch-depth: 0
      - name: Set variables
        run: |
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: latest
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: Publish
        run: |
          cd dist || exit 1
          git init --initial-branch=gh-pages
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "${COMMIT}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin gh-pages